### PR TITLE
Migrate from NTOSpider to APPSpider with additional evidence fields

### PR DESCRIPTION
**Pull request by mgargiullo**
We had clone this repo shortly after Rapid 7 bought NT Objectives and made a few additions to the available evidence fields.  We found that AppSpider didn't consistently populate the same fields in their XML structure.  It also tended to include an Attack xml structure per attempt.  The NTOSpider plugin only grabbed the first instance well.

This PR is the result of forking your NTOSpider repo, and making our naming and evidence changes available.

### CODE REVIEW

**Comment by rachkor** [comment]
@mgargiullo I apologize for the delay! I'm starting to review this right now and just realized that we don't have a good spec file to use to test the new fields/XML format. Could you push one here?

**Comment by mgargiullo** [comment]
I'll push one in the morning.

**Comment by mgargiullo** [comment]
My turn to apologize.  I've updated and pushed a new spec file for this. 

I also updated my appspider repository with code that will work on the new Debian 9 vm. The new version of ruby didn't like the module naming convention, so 'AppSpider' was changed to 'Appspider' across the board in all ruby files.

**Comment by mgargiullo** [comment]
Closing this pull request to ensure everything is proper with Dradis v3.  I'll reopen a pull request once I have migrated changes properly and tested on my Staging server.

**Comment by dormi** [comment]
Hi @mgargiullo. I was thinking on reopening this and reusing what you already did.
Have you made some progress in another PR repo?

**Comment by mgargiullo** [comment]
@dormi . Sorry...  I haven't had a chance to touch it. Q4 has been absolutely insanely busy.
Please feel free to use anything/everything I've already put together.  I believe I updated our repo in November for Dradis 3 if you want/need to pull data: https://github.com/PivotPointSecurity/dradis-appspider

Thanks!

**Pull request closed without merging**
